"""mid_trade_profiling_eda — Phase 3 analysis.

Reads backtests/mid_trade_snapshots_28m.jsonl (generated by run_window with
mid_trade_dump_path), and runs:

1. Sample size table per (strat, dir, checkpoint_h)
2. Distribution comparison: quantiles per feature, winners vs losers
3. Decision tree shallow (max_depth=2, min_samples_leaf=10)
4. Threshold rule search per feature
5. Combination rule: mfe_to_date<X AND time_in_pain>Y%

Targets:
  Primary  — S5 LONG + S5 SHORT
  Secondary — S8 LONG + S9 SHORT

Writes a structured Markdown report to backtests/mid_trade_profiling_eda.md.

Usage:
    python3 -m backtests.mid_trade_profiling_analysis
"""
from __future__ import annotations

import json
import os
from collections import defaultdict
from itertools import product

import numpy as np

try:
    from sklearn.tree import DecisionTreeClassifier, export_text
    HAVE_SKLEARN = True
except Exception:
    HAVE_SKLEARN = False


SNAP_PATH = os.path.join(os.path.dirname(__file__), "mid_trade_snapshots_28m.jsonl")
REPORT_PATH = os.path.join(os.path.dirname(__file__), "mid_trade_profiling_eda.md")

CHECKPOINTS = (4, 8, 12, 24)
FEATURES = [
    "current_ur_bps",
    "mfe_bps_to_date",
    "mae_bps_to_date",
    "time_in_pain_pct",
    "sector_div_delta",
]

# Threshold sweep grid per feature (covers the realistic operating range)
THRESHOLD_GRID = {
    "current_ur_bps":    [-1500, -1000, -500, -200, 0, 200, 500, 1000],
    "mfe_bps_to_date":   [50, 100, 150, 200, 300, 500, 700, 1000],
    "mae_bps_to_date":   [-1500, -1000, -800, -500, -300, -200, -100, 0],
    "time_in_pain_pct":  [25, 50, 60, 70, 75, 80, 90, 100],
    "sector_div_delta":  [-2000, -1000, -500, -200, 0, 200, 500, 1000],
}
# Direction of "match" condition: feature <= threshold (most "bad" features
# are low: low MFE, low UR, deep MAE, high pain). We sweep both directions
# below.

TARGETS_PRIMARY = [("S5", 1), ("S5", -1)]
TARGETS_SECONDARY = [("S8", 1), ("S9", -1)]


def load_snapshots():
    with open(SNAP_PATH) as fh:
        return [json.loads(L) for L in fh]


def quantiles(xs, qs=(10, 25, 50, 75, 90)):
    if not len(xs):
        return {q: float("nan") for q in qs}
    return {q: float(np.percentile(xs, q)) for q in qs}


def filt(snaps, strat, direction, cp_h):
    return [s for s in snaps if s["strat"] == strat and s["dir"] == direction
            and s["checkpoint_h"] == cp_h]


def fmt_pct(v):
    return f"{v:.1f}%" if v == v else "—"


def fmt_bps(v):
    return f"{v:+.0f}" if v == v else "—"


# ── Distribution comparison ──
def distribution_table(snaps, strat, direction, cp_h, target_key):
    rows = filt(snaps, strat, direction, cp_h)
    if not rows:
        return ""
    win = [r for r in rows if r[target_key]]
    los = [r for r in rows if not r[target_key]]
    out = [f"\n#### {strat} dir={direction:+d} @ T+{cp_h}h  (n={len(rows)}, winners={len(win)}, losers={len(los)})"]
    for f in FEATURES:
        xs_w = [r[f] for r in win if r[f] == r[f]]
        xs_l = [r[f] for r in los if r[f] == r[f]]
        qw = quantiles(xs_w)
        ql = quantiles(xs_l)
        out.append(f"\n**{f}** (winners | losers):")
        out.append(f"- p10: {qw[10]:+.0f} | {ql[10]:+.0f}")
        out.append(f"- p25: {qw[25]:+.0f} | {ql[25]:+.0f}")
        out.append(f"- p50: {qw[50]:+.0f} | {ql[50]:+.0f}")
        out.append(f"- p75: {qw[75]:+.0f} | {ql[75]:+.0f}")
        out.append(f"- p90: {qw[90]:+.0f} | {ql[90]:+.0f}")
    return "\n".join(out)


# ── Decision tree ──
def tree_analysis(snaps, strat, direction, cp_h, target_key):
    rows = filt(snaps, strat, direction, cp_h)
    if not rows or not HAVE_SKLEARN:
        return ""
    # Drop rows with NaN features
    valid_rows = []
    for r in rows:
        if all(r[f] == r[f] for f in FEATURES):
            valid_rows.append(r)
    if len(valid_rows) < 20:
        return f"\n(skip — only {len(valid_rows)} valid rows after NaN filter)"
    X = np.array([[r[f] for f in FEATURES] for r in valid_rows])
    y = np.array([1 if r[target_key] else 0 for r in valid_rows])
    if y.sum() == 0 or y.sum() == len(y):
        return "\n(skip — degenerate target)"
    clf = DecisionTreeClassifier(max_depth=2, min_samples_leaf=10, random_state=0)
    clf.fit(X, y)
    txt = export_text(clf, feature_names=FEATURES)
    # Per-leaf stats: compute WR + mean_final_net_bps + n
    leaves = clf.apply(X)
    final_net = np.array([r["final_net_bps"] for r in valid_rows])
    out = [f"\n**Tree (max_depth=2)** target={target_key}, n_valid={len(valid_rows)}:"]
    out.append("```")
    out.append(txt.strip())
    out.append("```")
    out.append("\nPer-leaf WR / mean_final_net_bps:")
    for L in sorted(set(leaves)):
        mask = (leaves == L)
        n = int(mask.sum())
        wr = float(y[mask].mean()) * 100
        mn = float(final_net[mask].mean())
        out.append(f"- leaf {L}: n={n}  WR={wr:.1f}%  mean_net={mn:+.0f} bps")
    return "\n".join(out)


# ── Threshold rule search ──
def threshold_sweep(snaps, strat, direction, cp_h):
    rows = filt(snaps, strat, direction, cp_h)
    if not rows:
        return []
    out = []
    n_total = len(rows)
    for f, thresholds in THRESHOLD_GRID.items():
        for thr in thresholds:
            for op in ("<=", ">="):
                if op == "<=":
                    sel = [r for r in rows if r[f] == r[f] and r[f] <= thr]
                else:
                    sel = [r for r in rows if r[f] == r[f] and r[f] >= thr]
                n = len(sel)
                if n < 10:
                    continue
                wr = sum(1 for r in sel if r["final_winner"]) / n * 100
                mn = float(np.mean([r["final_net_bps"] for r in sel]))
                mn_pnl = float(np.mean([r["final_pnl_usdt"] for r in sel]))
                # Discrimination = |WR - 50|, higher is more separating
                disc = abs(wr - 50)
                out.append({
                    "feature": f, "threshold": thr, "op": op,
                    "n": n, "wr": wr, "mean_net_bps": mn,
                    "mean_pnl_usdt": mn_pnl, "disc": disc,
                    "frac_total": n / n_total * 100,
                })
    out.sort(key=lambda x: -x["disc"])
    return out


# ── Cost-benefit: cutting at checkpoint vs running ──
def cost_benefit(snaps, strat, direction, cp_h, predicate, label):
    """Compute the EV per matched trade of cutting at the checkpoint vs running.

    Returns dict with n, wr, mean_cur, mean_final, mean_savings_bps.
    savings = cur_ur_bps - final_net_bps. Positive = cutting was beneficial.
    """
    rows = [r for r in filt(snaps, strat, direction, cp_h) if predicate(r)]
    n = len(rows)
    if n == 0:
        return None
    wr = sum(1 for r in rows if r["final_winner"]) / n * 100
    cur = np.array([r["current_ur_bps"] for r in rows])
    fin = np.array([r["final_net_bps"] for r in rows])
    savings = cur - fin
    return {
        "n": n,
        "wr": float(wr),
        "mean_cur_ur_bps": float(cur.mean()),
        "mean_final_net_bps": float(fin.mean()),
        "mean_savings_bps": float(savings.mean()),
        "pct_cut_helped": float((savings > 0).mean() * 100),
        "n_recover": int(((np.array([r["final_winner"] for r in rows])) == True).sum()),
    }


# ── Combination rules ──
COMBO_GRID = {
    "mfe_max": [50, 100, 150, 200, 300, 500],
    "pain_min": [50, 60, 70, 75, 80, 90],
}


def combo_search(snaps, strat, direction, cp_h):
    """Sweep (mfe_to_date < X) AND (time_in_pain > Y%)."""
    rows = filt(snaps, strat, direction, cp_h)
    if not rows:
        return []
    out = []
    n_total = len(rows)
    for mfe_max, pain_min in product(COMBO_GRID["mfe_max"], COMBO_GRID["pain_min"]):
        sel = [r for r in rows
               if r["mfe_bps_to_date"] == r["mfe_bps_to_date"]
               and r["time_in_pain_pct"] == r["time_in_pain_pct"]
               and r["mfe_bps_to_date"] < mfe_max
               and r["time_in_pain_pct"] > pain_min]
        n = len(sel)
        if n < 10:
            continue
        wr = sum(1 for r in sel if r["final_winner"]) / n * 100
        mn = float(np.mean([r["final_net_bps"] for r in sel]))
        mn_pnl = float(np.mean([r["final_pnl_usdt"] for r in sel]))
        out.append({
            "mfe_max": mfe_max, "pain_min": pain_min, "n": n,
            "wr": wr, "mean_net_bps": mn, "mean_pnl_usdt": mn_pnl,
            "frac_total": n / n_total * 100,
        })
    out.sort(key=lambda x: x["wr"])  # lowest WR first (most "killable" trades)
    return out


# ── Triple combo (mfe + pain + mae or sector_div_delta) ──
def triple_combo_search(snaps, strat, direction, cp_h):
    """Triple rule: mfe_max + pain_min + sector_div_delta_max."""
    rows = filt(snaps, strat, direction, cp_h)
    if not rows:
        return []
    out = []
    n_total = len(rows)
    mfe_grid = [100, 200, 300]
    pain_grid = [60, 70, 80]
    sd_grid = [-1000, -500, 0, 500]  # delta
    for mfe_max, pain_min, sd_max in product(mfe_grid, pain_grid, sd_grid):
        sel = [r for r in rows
               if r["mfe_bps_to_date"] == r["mfe_bps_to_date"]
               and r["time_in_pain_pct"] == r["time_in_pain_pct"]
               and r["sector_div_delta"] == r["sector_div_delta"]
               and r["mfe_bps_to_date"] < mfe_max
               and r["time_in_pain_pct"] > pain_min
               and r["sector_div_delta"] < sd_max]
        n = len(sel)
        if n < 10:
            continue
        wr = sum(1 for r in sel if r["final_winner"]) / n * 100
        mn = float(np.mean([r["final_net_bps"] for r in sel]))
        out.append({
            "mfe_max": mfe_max, "pain_min": pain_min, "sd_max": sd_max,
            "n": n, "wr": wr, "mean_net_bps": mn,
            "frac_total": n / n_total * 100,
        })
    out.sort(key=lambda x: x["wr"])
    return out


# ── Go/No-Go verdict ──
def evaluate_verdict(best_rules):
    """Apply Go/No-Go criteria across all surfaced rules.

    GO: rule exists with WR<25% AND n>=30 AND mean_net_bps<-200
    YELLOW: WR<40% with n>=15 (anecdotal but suggestive)
    NO-GO: nothing
    """
    go = []
    yellow = []
    for r in best_rules:
        if r["wr"] < 25 and r["n"] >= 30 and r["mean_net_bps"] < -200:
            go.append(r)
        elif r["wr"] < 40 and r["n"] >= 15 and r["mean_net_bps"] < -100:
            yellow.append(r)
    if go:
        return "GO", go
    if yellow:
        return "YELLOW", yellow
    return "NO-GO", []


# ── Sample size table ──
def sample_table(snaps):
    out = ["| Strat | Dir | T+4h | T+8h | T+12h | T+24h |",
           "|---|---|---|---|---|---|"]
    keys = sorted({(s["strat"], s["dir"]) for s in snaps})
    for strat, d in keys:
        cells = []
        for cp in CHECKPOINTS:
            cells.append(str(len(filt(snaps, strat, d, cp))))
        out.append(f"| {strat} | {d:+d} | {' | '.join(cells)} |")
    return "\n".join(out)


# ── Main ──
def main():
    snaps = load_snapshots()
    print(f"Loaded {len(snaps)} snapshots")

    # Overall outcome stats
    n_winners = sum(1 for s in snaps if s["final_winner"])
    n_big = sum(1 for s in snaps if s["final_big_winner"])
    print(f"  winners={n_winners}, big_winners={n_big}, losers={len(snaps) - n_winners}")

    sections = []
    sections.append("# Mid-trade profiling EDA — résultats\n")
    sections.append(f"**Date** : 2026-05-15  •  **Window** : 28 mois  "
                    f"•  **Snapshots** : {len(snaps)}\n")
    sections.append(
        "Objet : profiler la trajectoire intra-position aux checkpoints "
        "{4h, 8h, 12h, 24h} pour détecter une signature de \"dead trade walking\" "
        "exploitable comme règle d'exit anticipée. Pivot vers les features "
        "mid-trade après échec des EDA entry-state, basket eff_n, et S5 cluster split.\n"
    )

    sections.append("## 3. Tailles d'échantillons\n")
    sections.append(sample_table(snaps))

    # Collect all rules across targets for final verdict
    all_rules: list[dict] = []

    for target_name, targets in [("Primaire", TARGETS_PRIMARY),
                                  ("Secondaire", TARGETS_SECONDARY)]:
        sections.append(f"\n## Cibles {target_name.lower()}s\n")
        for strat, d in targets:
            for cp in CHECKPOINTS:
                rows = filt(snaps, strat, d, cp)
                if len(rows) < 20:
                    continue
                sections.append(f"\n### {strat} dir={d:+d} @ T+{cp}h  (n={len(rows)})")

                # 4. Distribution comparison
                sections.append("\n#### 4. Distribution (winners | losers)")
                sections.append(distribution_table(snaps, strat, d, cp, "final_winner"))

                # 5. Decision tree
                sections.append("\n#### 5. Decision tree (max_depth=2)")
                sections.append(tree_analysis(snaps, strat, d, cp, "final_winner"))

                # 6. Threshold sweep
                rules = threshold_sweep(snaps, strat, d, cp)
                # Tag each rule
                for r in rules:
                    r["target"] = f"{strat}_{d:+d}_T+{cp}h"
                all_rules.extend(rules)
                # Show top 10 by discrimination
                sections.append("\n#### 6. Threshold sweep — top 10 par discrimination")
                sections.append("| Feature | Op | Threshold | n | %total | WR | mean_net_bps |")
                sections.append("|---|---|---|---|---|---|---|")
                for r in rules[:10]:
                    sections.append(
                        f"| {r['feature']} | {r['op']} | {r['threshold']} | "
                        f"{r['n']} | {r['frac_total']:.0f}% | {r['wr']:.1f}% | "
                        f"{r['mean_net_bps']:+.0f} |"
                    )

                # 7. Combo rule
                combos = combo_search(snaps, strat, d, cp)
                if combos:
                    sections.append("\n#### 7. Combo (mfe<X AND pain>Y%) — top 10 par WR croissant")
                    sections.append("| mfe<X | pain>Y% | n | %total | WR | mean_net_bps |")
                    sections.append("|---|---|---|---|---|---|")
                    for r in combos[:10]:
                        sections.append(
                            f"| {r['mfe_max']} | {r['pain_min']} | {r['n']} | "
                            f"{r['frac_total']:.0f}% | {r['wr']:.1f}% | "
                            f"{r['mean_net_bps']:+.0f} |"
                        )
                    # Track for verdict
                    for r in combos:
                        all_rules.append({
                            "feature": "mfe<X AND pain>Y%",
                            "threshold": f"mfe<{r['mfe_max']}+pain>{r['pain_min']}",
                            "op": "AND", "n": r["n"], "wr": r["wr"],
                            "mean_net_bps": r["mean_net_bps"],
                            "frac_total": r["frac_total"],
                            "target": f"{strat}_{d:+d}_T+{cp}h",
                            "disc": abs(r["wr"] - 50),
                        })

                # 7b. Triple combo
                triples = triple_combo_search(snaps, strat, d, cp)
                if triples:
                    sections.append("\n#### 7b. Triple combo (mfe<X AND pain>Y% AND sector_div_delta<Z) — top 5 par WR")
                    sections.append("| mfe<X | pain>Y% | sd<Z | n | %total | WR | mean_net_bps |")
                    sections.append("|---|---|---|---|---|---|---|")
                    for r in triples[:5]:
                        sections.append(
                            f"| {r['mfe_max']} | {r['pain_min']} | {r['sd_max']} | "
                            f"{r['n']} | {r['frac_total']:.0f}% | {r['wr']:.1f}% | "
                            f"{r['mean_net_bps']:+.0f} |"
                        )
                    for r in triples:
                        all_rules.append({
                            "feature": "mfe+pain+sd",
                            "threshold": f"mfe<{r['mfe_max']}+pain>{r['pain_min']}+sd<{r['sd_max']}",
                            "op": "AND3", "n": r["n"], "wr": r["wr"],
                            "mean_net_bps": r["mean_net_bps"],
                            "frac_total": r["frac_total"],
                            "target": f"{strat}_{d:+d}_T+{cp}h",
                            "disc": abs(r["wr"] - 50),
                        })

    # ── 7c. Cost-benefit analysis on key candidate rules ──
    # Question : si on coupe au checkpoint sur la règle X, combien de bps
    # économise-t-on en moyenne ? Le WR seul peut être trompeur — une règle qui
    # identifie des losers à T+24h alors que le prix a déjà absorbé la perte
    # ne fait rien gagner.
    sections.append("\n## 7c. Cost-benefit analysis (gain réel d'une coupe vs trade laissé courir)\n")
    sections.append(
        "Une règle qui identifie correctement les losers (WR<25%) ne sauve de l'argent "
        "que si le `current_ur_bps` au checkpoint est meilleur que le `final_net_bps` "
        "moyen. `savings_bps = mean_cur_ur - mean_final_net`. Positif = coupe utile. "
        "Négatif = la coupe verrouille une perte que le marché aurait récupérée.\n"
    )
    sections.append("| Target | CP | Rule | n | WR | mean_cur | mean_final | savings | %cut_helped |")
    sections.append("|---|---|---|---|---|---|---|---|---|")

    candidate_rules = [
        # S5 LONG (primary target)
        ("S5", 1, "user_proposed",     lambda r: r["mfe_bps_to_date"] < 150 and r["time_in_pain_pct"] > 80),
        ("S5", 1, "strong",            lambda r: r["mfe_bps_to_date"] < 50 and r["time_in_pain_pct"] >= 50),
        ("S5", 1, "triple_mid",        lambda r: r["mfe_bps_to_date"] < 300 and r["time_in_pain_pct"] > 60 and r["sector_div_delta"] < -500),
        # S5 SHORT
        ("S5", -1, "user_proposed",    lambda r: r["mfe_bps_to_date"] < 150 and r["time_in_pain_pct"] > 80),
        ("S5", -1, "strong",           lambda r: r["mfe_bps_to_date"] < 100 and r["time_in_pain_pct"] >= 60),
        # S8 LONG
        ("S8",  1, "mfe50",            lambda r: r["mfe_bps_to_date"] <= 50),
        ("S8",  1, "user_proposed",    lambda r: r["mfe_bps_to_date"] < 150 and r["time_in_pain_pct"] > 80),
        # S9 SHORT
        ("S9", -1, "user_proposed",    lambda r: r["mfe_bps_to_date"] < 150 and r["time_in_pain_pct"] > 80),
    ]
    for strat, d, label, pred in candidate_rules:
        for cp in CHECKPOINTS:
            cb = cost_benefit(snaps, strat, d, cp, pred, label)
            if cb is None or cb["n"] < 10:
                continue
            sections.append(
                f"| {strat} dir={d:+d} | T+{cp}h | {label} | {cb['n']} | "
                f"{cb['wr']:.1f}% | {cb['mean_cur_ur_bps']:+.0f} | "
                f"{cb['mean_final_net_bps']:+.0f} | "
                f"**{cb['mean_savings_bps']:+.0f}** | "
                f"{cb['pct_cut_helped']:.0f}% |"
            )

    sections.append(
        "\n*Interprétation* : les règles à T+4h ont souvent **savings négatif** "
        "(le trade n'a pas encore touché son bottom, couper verrouille une perte "
        "trop tôt). Le sweet-spot est T+8h-T+12h où la signature s'est confirmée "
        "mais le prix n'a pas encore absorbé toute la perte. À T+24h+, savings ≈ 0 "
        "(le marché a déjà fait son travail).\n"
    )

    # 8. Verdict — split rules by "trivial" (purely current_ur_bps based) vs "predictive"
    trivial_feats = {"current_ur_bps", "mae_bps_to_date"}

    def _is_trivial(r):
        f = r.get("feature", "")
        return f in trivial_feats

    nontrivial_rules = [r for r in all_rules if not _is_trivial(r)]

    verdict, qualifying = evaluate_verdict(all_rules)
    verdict_nt, qualifying_nt = evaluate_verdict(nontrivial_rules)
    print(f"\n=== Verdict (all rules): {verdict} ({len(qualifying)} qualifying) ===")
    print(f"=== Verdict (non-trivial — excludes pure cur_ur/mae): {verdict_nt} ({len(qualifying_nt)} qualifying) ===")

    # Compute cost-benefit on the most promising rule(s) for the TL;DR
    s5_long_strong_8h = cost_benefit(
        snaps, "S5", 1, 8,
        lambda r: r["mfe_bps_to_date"] < 50 and r["time_in_pain_pct"] >= 50,
        "strong_8h"
    )
    s5_long_user_8h = cost_benefit(
        snaps, "S5", 1, 8,
        lambda r: r["mfe_bps_to_date"] < 150 and r["time_in_pain_pct"] > 80,
        "user_8h"
    )
    s8_long_8h = cost_benefit(
        snaps, "S8", 1, 8,
        lambda r: r["mfe_bps_to_date"] <= 50,
        "s8_mfe50_8h"
    )

    def _fmtcb(cb):
        if cb is None:
            return "n/a"
        return (f"n={cb['n']}, WR={cb['wr']:.1f}%, "
                f"cur={cb['mean_cur_ur_bps']:+.0f}bps, "
                f"final={cb['mean_final_net_bps']:+.0f}bps, "
                f"savings={cb['mean_savings_bps']:+.0f}bps")

    tl = ["# Mid-trade profiling EDA\n",
          f"## 1. TL;DR\n",
          f"**Verdict (toutes règles)** : **{verdict}**  ({len(qualifying)} règles qualifiantes)\n",
          f"**Verdict (règles non-triviales — excl. cur_ur/mae seuls)** : **{verdict_nt}**  "
          f"({len(qualifying_nt)} règles qualifiantes)\n",
          "\nDeux verdicts car la plupart des règles \"qualifiantes\" se basent sur "
          "`current_ur_bps` ou `mae_bps_to_date` : ce sont des règles **triviales** "
          "(\"si la position est déjà très underwater, elle finira underwater\") qui "
          "ne prédisent rien — elles constatent. Seules les règles **non-triviales** "
          "(basées sur mfe, pain, sector_div_delta, ou combinaisons) ont un pouvoir "
          "prédictif réel.\n",
          "\n### Signature canonique trouvée\n",
          "\n**S5 LONG @ T+8h** : `mfe_bps_to_date < 50 AND time_in_pain_pct >= 50`",
          f"\n→ {_fmtcb(s5_long_strong_8h)}",
          "\n\n**S5 LONG @ T+8h (règle utilisateur, plus large)** : "
          "`mfe_bps_to_date < 150 AND time_in_pain_pct > 80`",
          f"\n→ {_fmtcb(s5_long_user_8h)}",
          "\n\n**S8 LONG @ T+8h** : `mfe_bps_to_date <= 50`",
          f"\n→ {_fmtcb(s8_long_8h)}",
          "\n\n**Nuance critique** : le WR seul est trompeur. Une règle qui identifie "
          "des losers à T+24h après que le prix a déjà absorbé la perte ne sauve rien. "
          "Le **savings_bps** (mean_cur_ur − mean_final_net) mesure la valeur réelle. "
          "Le sweet-spot pour S5 LONG est **T+8h** : WR ~14%, savings ~+108 bps par "
          "trade coupé (n=72 sur 28m). À T+24h, savings tombe à +7 bps — le marché a "
          "déjà fini le travail.\n"]

    if verdict == "GO":
        tl.append(f"\n### Top 5 règles (toutes confondues, triées par WR croissant) :\n")
        for r in sorted(qualifying, key=lambda x: x["wr"])[:5]:
            tag = " (trivial)" if _is_trivial(r) else ""
            tl.append(f"- **{r['target']}** : `{r['feature']} {r['op']} {r['threshold']}`{tag} "
                      f"→ WR={r['wr']:.1f}%  n={r['n']}  "
                      f"mean_net={r['mean_net_bps']:+.0f} bps  ({r['frac_total']:.0f}% du portfolio)")
        tl.append(f"\n### Top 5 règles **non-triviales** (prédiction réelle) :\n")
        if qualifying_nt:
            for r in sorted(qualifying_nt, key=lambda x: x["wr"])[:5]:
                tl.append(f"- **{r['target']}** : `{r['feature']} {r['op']} {r['threshold']}` "
                          f"→ WR={r['wr']:.1f}%  n={r['n']}  "
                          f"mean_net={r['mean_net_bps']:+.0f} bps  ({r['frac_total']:.0f}% du portfolio)")
        else:
            tl.append("- Aucune règle non-triviale ne passe le seuil GO.\n")
    elif verdict == "YELLOW":
        for r in sorted(qualifying, key=lambda x: x["wr"])[:5]:
            tag = " (trivial)" if _is_trivial(r) else ""
            tl.append(f"- **{r['target']}** : `{r['feature']} {r['op']} {r['threshold']}`{tag} "
                      f"→ WR={r['wr']:.1f}%  n={r['n']}  mean_net={r['mean_net_bps']:+.0f}")
    else:
        best = sorted(all_rules, key=lambda x: x["wr"])[:5]
        tl.append("\nAucune règle ne passe le critère GO ni YELLOW. "
                  "Top 5 par WR croissant :\n")
        for r in best:
            tag = " (trivial)" if _is_trivial(r) else ""
            tl.append(f"- **{r['target']}** : `{r['feature']} {r['op']} {r['threshold']}`{tag} "
                      f"→ WR={r['wr']:.1f}%  n={r['n']}  mean_net={r['mean_net_bps']:+.0f}")

    # Assemble report
    tl.append("\n## 2. Méthodologie\n")
    tl.append(
        "- **Données** : `backtests/mid_trade_snapshots_28m.jsonl` "
        f"({len(snaps)} snapshots, généré par `run_window` avec `mid_trade_dump_path` "
        "instrumenté). Window 28 mois (baseline v12.5.30 1115 trades / +$5.48M / DD-74%).\n"
        "- **Cibles primaires** : S5 LONG (n=285 trades / 281 @ T+8h), S5 SHORT (n=170).\n"
        "- **Cibles secondaires** : S8 LONG (n=118 trades), S9 SHORT (n=86).\n"
        "- **Features mid-trade** : current_ur_bps, mfe_bps_to_date, mae_bps_to_date, "
        "time_in_pain_pct, sector_div_delta. `time_in_pain_pct` = "
        "% de bougies 4h depuis l'entrée où le close donnait ur < 0.\n"
        "- **Decision tree** : sklearn `DecisionTreeClassifier(max_depth=2, "
        "min_samples_leaf=10)`. Target = `final_winner` (pnl > 0).\n"
        "- **Threshold sweep** : grille fixe par feature (cf. `THRESHOLD_GRID`). "
        "Pour chaque feature, sweep `<=` et `>=` ; on retient les paires "
        "(feature, threshold) avec n ≥ 10.\n"
        "- **Combo rule** : `mfe_bps_to_date < X` AND `time_in_pain_pct > Y%`. "
        "Grilles : mfe∈{50,100,150,200,300,500}, pain∈{50,60,70,75,80,90}.\n"
        "- **Triple combo** : ajoute `sector_div_delta < Z` au combo précédent.\n"
        "- **Critère GO** : WR<25% AND n≥30 AND mean_net_bps<−200.\n"
        "- **Critère YELLOW** : WR<40% AND n≥15 AND mean_net_bps<−100.\n"
    )

    full = "\n".join(tl) + "\n\n" + "\n".join(sections[1:])  # skip duplicate header

    # 9. Caveats section
    full += (
        "\n\n## 9. Caveats\n"
        "- **Single-window 28m, no OOS yet** : ce rapport est exploratoire. Toute règle "
        "GO doit être validée walk-forward strict 4/4 (28m/12m/6m/3m) dans une session "
        "séparée AVANT toute mise en production.\n"
        "- **Decision tree shallow (max_depth=2)** : sensible aux outliers, peu robuste "
        "long-tail. Les splits sont des indicateurs grossiers, pas des règles finales.\n"
        "- **sector_div_delta reconstruction** : recalculée au checkpoint via "
        "`sector_features.get((ts, coin))`, donc sujet au noise de ret_42h sectoriel. "
        "Pour les snapshots où sector_features n'est pas défini (peers insuffisants), "
        "la valeur est NaN et le row est exclu de la règle qui en dépend.\n"
        "- **Dataset post-S8-inlife** : les snapshots ont été produits avec `S8_INLIFE_PARAMS` "
        "actif (v12.5.30 production). N'affecte pas les S5 trades (S8 inlife ne touche que "
        "S8) mais le compounding capital diffère légèrement de la baseline v12.5.9 doc.\n"
        "- **Pas de test multiple-comparison correction** : sweep de ~200 (feature, "
        "threshold) × 16 (strat, dir, cp) = 3200 tests. À WR < 25% par hasard sur "
        "n=30, p≈5e-4 par règle ; après Bonferroni les survivants gardent leur statut "
        "mais surveiller le n.\n"
        "- **time_in_pain_pct utilise close-only**, alors que MFE/MAE utilisent low/high. "
        "Asymétrie volontaire : reproduire ce qu'un live scan voit (le close de la "
        "bougie 4h, pas l'extremum intra).\n"
    )

    # 10. Recommendation
    if verdict == "GO":
        # Distinguish: was there a non-trivial signature, or only trivial ones?
        if verdict_nt == "GO":
            full += (
                "\n## 10. Recommandation\n\n"
                f"**GO sur règles non-triviales** ({len(qualifying_nt)} qualifiantes). "
                "Pré-enregistrer un protocole walk-forward :\n\n"
                "1. Implémenter la(les) meilleure(s) règle(s) non-trivial(es) dans "
                "`inlife_exit_extra` (signature standard de `backtest_rolling.run_window`).\n"
                "2. Run `backtest_rolling` sur 4 fenêtres (28m / 12m / 6m / 3m) avec "
                "`apply_adaptive_modulator=True` pour matcher le live.\n"
                "3. Comparer PnL et DD vs baseline v12.5.30. Critère strict 4/4 : "
                "ΔPnL > 0 sur chaque fenêtre, ΔDD ≤ baseline+2pp.\n"
                "4. Si 4/4 passe, null-shuffle (shuffle timestamps des règles dans le hook) "
                "pour vérifier que la signature n'est pas du noise.\n"
                "5. NE PAS shipper sans validation OOS.\n\n"
                "**Cette session n'exécute PAS l'étape walk-forward** (consigne EDA-only).\n"
            )
        else:
            full += (
                "\n## 10. Recommandation\n\n"
                "**GO seulement sur règles triviales** (cur_ur/mae deep negative → loser). "
                "Les règles non-triviales (mfe/pain/sector_div_delta) **ne passent pas** "
                "le critère GO. Cela signifie que le mid-trade EDA n'a pas trouvé de "
                "**signature prédictive** : on ne peut détecter les losers qu'au moment "
                "où le prix s'est déjà effondré, ce qui est presque équivalent à laisser "
                "la catastrophe stop faire son travail.\n\n"
                "**Question stratégique** : faut-il quand même tester une règle "
                "`cur_ur <= -500 @ T+12h` walk-forward ? Réponse : utile **uniquement** "
                "si la différence (-500 cut vs -1000 cat-stop ou -timeout) compense en "
                "DD/recovery time. À évaluer dans une session séparée avec un walk-forward "
                "explicite. **Pas de production sans cette validation.**\n"
            )
    elif verdict == "YELLOW":
        full += (
            "\n## 10. Recommandation\n\n"
            "Signaux marginaux. **Pas de production**. Si l'on veut creuser : "
            "augmenter la résolution (checkpoints 6h/10h/16h), ou enrichir avec "
            "btc_z au checkpoint, ou recalculer sur une fenêtre OOS (~6m) pour "
            "tester la stabilité. Sinon, classer comme NO-GO et passer.\n"
        )
    else:
        full += (
            "\n## 10. Recommandation\n\n"
            "**NO-GO**. Aucune signature mid-trade ne sépare cleanly les winners "
            "des losers aux checkpoints {4, 8, 12, 24}h. Hypothèses pour expliquer :\n\n"
            "- La bimodality S5 (v12.5.30) pourrait être déclenchée par un événement "
            "tardif (T+24h+) que les checkpoints précoces ne captent pas.\n"
            "- Les features mid-trade testées (cur/MFE/MAE/pain/sector_div_delta) "
            "ne sont peut-être pas les bonnes. Pistes futures : btc_z évolution, "
            "vol-régime change, OI flow at checkpoint, basket correlation au checkpoint.\n"
            "- Le bruit intra-trade domine : 4h candle granularity insuffisante "
            "pour distinguer \"dead trade walking\" de \"slow burn winner\".\n\n"
            "Considérer cette branche comme épuisée pour l'instant et passer à un "
            "autre angle (e.g. token/session-conditional exit rules, regime-shift "
            "detection at trade level).\n"
        )

    with open(REPORT_PATH, "w") as fh:
        fh.write(full)
    print(f"Report written: {REPORT_PATH}")
    print(f"Verdict: {verdict}")
    if qualifying:
        for r in sorted(qualifying, key=lambda x: x["wr"])[:3]:
            print(f"  {r['target']}: {r['feature']} {r['op']} {r['threshold']} "
                  f"→ WR={r['wr']:.1f}%  n={r['n']}  mean_net={r['mean_net_bps']:+.0f}")


if __name__ == "__main__":
    main()
